### PR TITLE
main commit

### PR DESCRIPTION
**Pull request by richardwilliamson**
Adds in support for ‘f’ and ’t’ tags,
Adds a class parser method to check whether a string partially matches
an osc address
Adds support for non SLIP data - set useSLP to false. Should probably
rename to useSLIP but I mis-typed and ran with it

### CODE REVIEW

**Comment by ChrisAshworth** [comment]
This is cool Richard! 

I'd want to adjust a few things (at least whitespace and spelling) rather than merge directly as-is, but I'm imagining I could use this as a reference for implementing the same features.

(Since F53OSC is directly shipped in QLab I'm going to be very picky about what exactly gets merged, but this is still useful as a way to prod the addition of these features even if they might not get merged as-is, so thank you!)

I do not know an exact ETA of when I could attempt to merge a similar change, but wanted to thank you for submitting the pull request, and hopefully I can take a look before too long.

**Comment by richardwilliamson** [comment]
Thanks Chris - sounds good to me, feel free to fix my tabs and spelling! I will keep on using my branch for now and if you to merge it in then I can switch back to yours etc. 

Thanks

Richard

**Comment by codekrafter** [comment]
Any update on this? I have having the library throw errors when ever it receives a T or F type from eos.

**Comment by ChrisAshworth** [comment]
Thanks for the bump @codekrafter — we are working on an alternate branch for supporting T/F arguments over at https://github.com/Figure53/F53OSC/pull/23

**Comment by balord** [comment]
@richardwilliamson - If you are curious, I have also split off handling of TCP non-SLIP framing (OSC 1.0) into its own branch [`17-tcp-osc-1.0-framing`](https://github.com/Figure53/F53OSC/tree/17-tcp-osc-1.0-framing).

Full disclosure -- that branch is untested and might not be something we decide to merge. It should be considered experimental for now.

**Pull request closed without merging**
