### PR TITLE
Add Package.swift

### PR DESCRIPTION
**Pull request by pixlwave**
Hey

Not sure if you're interested in this, but I've added a Package.swift file so F53OSC can be added to an Xcode project as a Swift package.

**Caveat:** I couldn't for the life of me manage to make it work if all the source files were in the root directory. I just followed the standard SwiftPM file layout, but happy to tweak it if you would prefer something better. Also, I'm not very familiar with podspecs, so not sure if that will need tweaking too?

No worries if not 🙂

### CODE REVIEW

**Comment by balord** [comment]
Hi Doug -- thanks for the nudge on this!

We aren't using Swift Package Manager internally yet, so I'm afraid we don't have a good way to test this PR.

I did take the opportunity while we are doing these other updates to at least reorganize the file structure, in anticipation that likely someday we'll want to add a manifest file. I also rebuilt/renamed the Xcode project file to extract the library files from the "F53OSC Monitor" test app, along with adding a few other goodies like build targets for standalone frameworks, etc.

Since we don't have a good way to review this, for the time being, I'm going to close this PR without merging into our branch. But I would love to hear whether the new layout still works for your purposes and if you find any other adjustments are needed.

Thanks again!

**Comment by pixlwave** [comment]
Hey Brent, thanks for looking into this and no worries that you’re not able to merge at this point.

I created a fresh [fork](https://github.com/pixlwave/F53OSC) and dropped in a manifest file and it worked straight out of the box, so it should be simple enough for me to merge any changes you make from now on 👍🏻

The only thing that jumps to mind about the layout now is possibly moving CocoaAsyncSocket into its own directory (or making it a cocoapod dependency) but again I presume there’s internal reasons for having it this way 🙂

**Comment by balord** [comment]
That's great to hear it worked! 

Good point about the dependency files. In light of that, I made a few more changes to the file structure and moved the CocoaAsyncSocket files to their own "Vendor/CocoaAsyncSocket" subfolder in "Sources". I also realized I could eliminate the redundant "F53OSC" subdirectory, effectively moving "Sources" and "Tests" to the root level of the repo.

For now it seems simplest to keep the "F53OSC Monitor" app in its own subdirectory, since I can't tell if/when support for Resources in a Package.manifest will arrive.

**Comment by pixlwave** [comment]
> I made a few more changes to the file structure and moved the CocoaAsyncSocket files to their own "Vendor/CocoaAsyncSocket" subfolder in "Sources".

Thanks very much. I've added CocoaAsyncSocket as a dependency in the Swift manifest to avoid any conflicts in the wild.

> I also realized I could eliminate the redundant "F53OSC" subdirectory, effectively moving "Sources" and "Tests" to the root level of the repo.

This is great! The project now has the expected layout for the source files so SwiftPM doesn't need a custom path any more 👍🏻

I've added a 1.1.0 tag to the fork so if you'd like to try it out on a test project, it's now as easy as `File | Swift Packages | Add Package Dependency...` paste the repo url and Next, Next, Next your way to some OSC goodness!

> For now it seems simplest to keep the "F53OSC Monitor" app in its own subdirectory, since I can't tell if/when support for Resources in a Package.manifest will arrive.

Sounds sensible to me. 🤞🏻 we'll see it in beta in June!

**Pull request closed without merging**
